// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearRecordingsDir():Promise<string>;

export function GetAudioDevices():Promise<Array<main.AudioDevice>>;

export function GetGroqAPIKey():Promise<string>;

export function GetModel():Promise<string>;

export function GetTranscriptionHistory():Promise<Array<main.Transcription>>;

export function Greet(arg1:string):Promise<string>;

export function IsRecording():Promise<boolean>;

export function SetGroqAPIKey(arg1:string):Promise<string>;

export function SetModel(arg1:string):Promise<string>;

export function SetSelectedDevice(arg1:string):Promise<void>;

export function StartRecordingMicrophone():Promise<string>;

export function StopRecordingMicrophone():Promise<string>;
