// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearRecordingsDir() {
  return window['go']['main']['App']['ClearRecordingsDir']();
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetGroqAPIKey() {
  return window['go']['main']['App']['GetGroqAPIKey']();
}

export function GetModel() {
  return window['go']['main']['App']['GetModel']();
}

export function GetTranscriptionHistory() {
  return window['go']['main']['App']['GetTranscriptionHistory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsRecording() {
  return window['go']['main']['App']['IsRecording']();
}

export function SetGroqAPIKey(arg1) {
  return window['go']['main']['App']['SetGroqAPIKey'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetSelectedDevice(arg1) {
  return window['go']['main']['App']['SetSelectedDevice'](arg1);
}

export function StartRecordingMicrophone() {
  return window['go']['main']['App']['StartRecordingMicrophone']();
}

export function StopRecordingMicrophone() {
  return window['go']['main']['App']['StopRecordingMicrophone']();
}
